// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: bridge.proto

package bridgev1

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthResponse_ServingStatus int32

const (
	HealthResponse_UNKNOWN     HealthResponse_ServingStatus = 0
	HealthResponse_SERVING     HealthResponse_ServingStatus = 1
	HealthResponse_NOT_SERVING HealthResponse_ServingStatus = 2
)

// Enum value maps for HealthResponse_ServingStatus.
var (
	HealthResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthResponse_ServingStatus) Enum() *HealthResponse_ServingStatus {
	p := new(HealthResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_bridge_proto_enumTypes[0].Descriptor()
}

func (HealthResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_bridge_proto_enumTypes[0]
}

func (x HealthResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResponse_ServingStatus.Descriptor instead.
func (HealthResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{6, 0}
}

// 统一请求模型
// 业务方通过 gRPC 发送此请求，Bridge 解析 target 后路由到下游
type UnaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 目标服务标识，格式: "PackageName.ServiceName/MethodName"
	// 对应 gRPC 的 full method name，例如: "Hello.Greeter/SayHello"
	// Bridge 解析后，使用 "PackageName.ServiceName" 作为 etcd 服务名，"MethodName" 作为方法名
	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// 下游协议类型：GRPC / HTTP
	// Bridge 根据此字段选择对应的协议处理器转发请求
	Protocol string `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// 业务负载，使用 Any 实现零拷贝透传
	// 业务方将原始 protobuf Message 打包为 Any，Bridge 不感知具体 Schema
	Payload *anypb.Any `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// 调用元数据，透传给下游微服务（如 auth token、trace context、region 等）
	Metadata map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 超时配置（毫秒），覆盖全局默认值
	// 控制 Bridge 到下游微服务的调用超时
	TimeoutMs uint32 `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	// 重试策略
	Retry         *RetryPolicy `protobuf:"bytes,6,opt,name=retry,proto3" json:"retry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnaryRequest) Reset() {
	*x = UnaryRequest{}
	mi := &file_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryRequest) ProtoMessage() {}

func (x *UnaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryRequest.ProtoReflect.Descriptor instead.
func (*UnaryRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *UnaryRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *UnaryRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *UnaryRequest) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UnaryRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UnaryRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *UnaryRequest) GetRetry() *RetryPolicy {
	if x != nil {
		return x.Retry
	}
	return nil
}

type RetryPolicy struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MaxAttempts       uint32                 `protobuf:"varint,1,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`                    // 最大重试次数
	InitialBackoffMs  uint32                 `protobuf:"varint,2,opt,name=initial_backoff_ms,json=initialBackoffMs,proto3" json:"initial_backoff_ms,omitempty"`   // 初始退避时间
	BackoffMultiplier float32                `protobuf:"fixed32,3,opt,name=backoff_multiplier,json=backoffMultiplier,proto3" json:"backoff_multiplier,omitempty"` // 退避乘数
	RetryableCodes    []int32                `protobuf:"varint,4,rep,packed,name=retryable_codes,json=retryableCodes,proto3" json:"retryable_codes,omitempty"`    // 可重试的 gRPC 状态码
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RetryPolicy) Reset() {
	*x = RetryPolicy{}
	mi := &file_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicy) ProtoMessage() {}

func (x *RetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPolicy.ProtoReflect.Descriptor instead.
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *RetryPolicy) GetMaxAttempts() uint32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *RetryPolicy) GetInitialBackoffMs() uint32 {
	if x != nil {
		return x.InitialBackoffMs
	}
	return 0
}

func (x *RetryPolicy) GetBackoffMultiplier() float32 {
	if x != nil {
		return x.BackoffMultiplier
	}
	return 0
}

func (x *RetryPolicy) GetRetryableCodes() []int32 {
	if x != nil {
		return x.RetryableCodes
	}
	return nil
}

type UnaryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 成功响应负载（下游微服务返回的数据）
	Payload *anypb.Any `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// 响应元数据（从下游微服务透传回来）
	Metadata map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 如果调用失败，使用自定义 Status 错误模型
	// 包含路由失败、熔断打开、下游超时等错误
	Status *status.Status `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// 实际调用的下游微服务节点（用于调试和链路追踪）
	UpstreamNode string `protobuf:"bytes,4,opt,name=upstream_node,json=upstreamNode,proto3" json:"upstream_node,omitempty"`
	// 调用耗时（微秒），从 Bridge 接收到请求到返回响应的总时间
	LatencyUs     uint64 `protobuf:"varint,5,opt,name=latency_us,json=latencyUs,proto3" json:"latency_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnaryResponse) Reset() {
	*x = UnaryResponse{}
	mi := &file_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryResponse) ProtoMessage() {}

func (x *UnaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryResponse.ProtoReflect.Descriptor instead.
func (*UnaryResponse) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *UnaryResponse) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UnaryResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UnaryResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *UnaryResponse) GetUpstreamNode() string {
	if x != nil {
		return x.UpstreamNode
	}
	return ""
}

func (x *UnaryResponse) GetLatencyUs() uint64 {
	if x != nil {
		return x.LatencyUs
	}
	return 0
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *StreamRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *StreamRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *StreamRequest) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *anypb.Any             `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        *status.Status         `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *StreamResponse) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StreamResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"` // 空则检查 Bridge 自身
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *HealthRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthResponse struct {
	state           protoimpl.MessageState       `protogen:"open.v1"`
	Status          HealthResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=bridge.v1.HealthResponse_ServingStatus" json:"status,omitempty"`
	CheckedServices []string                     `protobuf:"bytes,2,rep,name=checked_services,json=checkedServices,proto3" json:"checked_services,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetStatus() HealthResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthResponse_UNKNOWN
}

func (x *HealthResponse) GetCheckedServices() []string {
	if x != nil {
		return x.CheckedServices
	}
	return nil
}

var File_bridge_proto protoreflect.FileDescriptor

const file_bridge_proto_rawDesc = "" +
	"\n" +
	"\fbridge.proto\x12\tbridge.v1\x1a\x19google/protobuf/any.proto\x1a\x17google/rpc/status.proto\"\xbf\x02\n" +
	"\fUnaryRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12.\n" +
	"\apayload\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\apayload\x12A\n" +
	"\bmetadata\x18\x04 \x03(\v2%.bridge.v1.UnaryRequest.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\rR\ttimeoutMs\x12,\n" +
	"\x05retry\x18\x06 \x01(\v2\x16.bridge.v1.RetryPolicyR\x05retry\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x01\n" +
	"\vRetryPolicy\x12!\n" +
	"\fmax_attempts\x18\x01 \x01(\rR\vmaxAttempts\x12,\n" +
	"\x12initial_backoff_ms\x18\x02 \x01(\rR\x10initialBackoffMs\x12-\n" +
	"\x12backoff_multiplier\x18\x03 \x01(\x02R\x11backoffMultiplier\x12'\n" +
	"\x0fretryable_codes\x18\x04 \x03(\x05R\x0eretryableCodes\"\xb0\x02\n" +
	"\rUnaryResponse\x12.\n" +
	"\apayload\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\apayload\x12B\n" +
	"\bmetadata\x18\x02 \x03(\v2&.bridge.v1.UnaryResponse.MetadataEntryR\bmetadata\x12*\n" +
	"\x06status\x18\x03 \x01(\v2\x12.google.rpc.StatusR\x06status\x12#\n" +
	"\rupstream_node\x18\x04 \x01(\tR\fupstreamNode\x12\x1d\n" +
	"\n" +
	"latency_us\x18\x05 \x01(\x04R\tlatencyUs\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf4\x01\n" +
	"\rStreamRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12.\n" +
	"\apayload\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\apayload\x12B\n" +
	"\bmetadata\x18\x04 \x03(\v2&.bridge.v1.StreamRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xee\x01\n" +
	"\x0eStreamResponse\x12.\n" +
	"\apayload\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\apayload\x12C\n" +
	"\bmetadata\x18\x02 \x03(\v2'.bridge.v1.StreamResponse.MetadataEntryR\bmetadata\x12*\n" +
	"\x06status\x18\x03 \x01(\v2\x12.google.rpc.StatusR\x06status\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\")\n" +
	"\rHealthRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xb8\x01\n" +
	"\x0eHealthResponse\x12?\n" +
	"\x06status\x18\x01 \x01(\x0e2'.bridge.v1.HealthResponse.ServingStatusR\x06status\x12)\n" +
	"\x10checked_services\x18\x02 \x03(\tR\x0fcheckedServices\":\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\xd5\x01\n" +
	"\rBridgeService\x12>\n" +
	"\tCallUnary\x12\x17.bridge.v1.UnaryRequest\x1a\x18.bridge.v1.UnaryResponse\x12E\n" +
	"\n" +
	"CallStream\x12\x18.bridge.v1.StreamRequest\x1a\x19.bridge.v1.StreamResponse(\x010\x01\x12=\n" +
	"\x06Health\x12\x18.bridge.v1.HealthRequest\x1a\x19.bridge.v1.HealthResponseB/Z-github.com/daheige/bridge-svc/api/v1;bridgev1b\x06proto3"

var (
	file_bridge_proto_rawDescOnce sync.Once
	file_bridge_proto_rawDescData []byte
)

func file_bridge_proto_rawDescGZIP() []byte {
	file_bridge_proto_rawDescOnce.Do(func() {
		file_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridge_proto_rawDesc), len(file_bridge_proto_rawDesc)))
	})
	return file_bridge_proto_rawDescData
}

var file_bridge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_bridge_proto_goTypes = []any{
	(HealthResponse_ServingStatus)(0), // 0: bridge.v1.HealthResponse.ServingStatus
	(*UnaryRequest)(nil),              // 1: bridge.v1.UnaryRequest
	(*RetryPolicy)(nil),               // 2: bridge.v1.RetryPolicy
	(*UnaryResponse)(nil),             // 3: bridge.v1.UnaryResponse
	(*StreamRequest)(nil),             // 4: bridge.v1.StreamRequest
	(*StreamResponse)(nil),            // 5: bridge.v1.StreamResponse
	(*HealthRequest)(nil),             // 6: bridge.v1.HealthRequest
	(*HealthResponse)(nil),            // 7: bridge.v1.HealthResponse
	nil,                               // 8: bridge.v1.UnaryRequest.MetadataEntry
	nil,                               // 9: bridge.v1.UnaryResponse.MetadataEntry
	nil,                               // 10: bridge.v1.StreamRequest.MetadataEntry
	nil,                               // 11: bridge.v1.StreamResponse.MetadataEntry
	(*anypb.Any)(nil),                 // 12: google.protobuf.Any
	(*status.Status)(nil),             // 13: google.rpc.Status
}
var file_bridge_proto_depIdxs = []int32{
	12, // 0: bridge.v1.UnaryRequest.payload:type_name -> google.protobuf.Any
	8,  // 1: bridge.v1.UnaryRequest.metadata:type_name -> bridge.v1.UnaryRequest.MetadataEntry
	2,  // 2: bridge.v1.UnaryRequest.retry:type_name -> bridge.v1.RetryPolicy
	12, // 3: bridge.v1.UnaryResponse.payload:type_name -> google.protobuf.Any
	9,  // 4: bridge.v1.UnaryResponse.metadata:type_name -> bridge.v1.UnaryResponse.MetadataEntry
	13, // 5: bridge.v1.UnaryResponse.status:type_name -> google.rpc.Status
	12, // 6: bridge.v1.StreamRequest.payload:type_name -> google.protobuf.Any
	10, // 7: bridge.v1.StreamRequest.metadata:type_name -> bridge.v1.StreamRequest.MetadataEntry
	12, // 8: bridge.v1.StreamResponse.payload:type_name -> google.protobuf.Any
	11, // 9: bridge.v1.StreamResponse.metadata:type_name -> bridge.v1.StreamResponse.MetadataEntry
	13, // 10: bridge.v1.StreamResponse.status:type_name -> google.rpc.Status
	0,  // 11: bridge.v1.HealthResponse.status:type_name -> bridge.v1.HealthResponse.ServingStatus
	1,  // 12: bridge.v1.BridgeService.CallUnary:input_type -> bridge.v1.UnaryRequest
	4,  // 13: bridge.v1.BridgeService.CallStream:input_type -> bridge.v1.StreamRequest
	6,  // 14: bridge.v1.BridgeService.Health:input_type -> bridge.v1.HealthRequest
	3,  // 15: bridge.v1.BridgeService.CallUnary:output_type -> bridge.v1.UnaryResponse
	5,  // 16: bridge.v1.BridgeService.CallStream:output_type -> bridge.v1.StreamResponse
	7,  // 17: bridge.v1.BridgeService.Health:output_type -> bridge.v1.HealthResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_bridge_proto_init() }
func file_bridge_proto_init() {
	if File_bridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridge_proto_rawDesc), len(file_bridge_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bridge_proto_goTypes,
		DependencyIndexes: file_bridge_proto_depIdxs,
		EnumInfos:         file_bridge_proto_enumTypes,
		MessageInfos:      file_bridge_proto_msgTypes,
	}.Build()
	File_bridge_proto = out.File
	file_bridge_proto_goTypes = nil
	file_bridge_proto_depIdxs = nil
}
